### PR TITLE
Cleanup and Organization

### PR DESCRIPTION
**Pull request by colanzio5**
@waltoncade Gotta meet to test and make sure everything still connects okay. Created a new echo server for client testing. It outputs random ducer/thermocouple/valve state data in an array. Will print any incoming relay commands if sent.

### CODE REVIEW

**Comment by alefir** [comment]
Since you said it still needs to be tested to see if everything connects, I'll merge this once it's been tested and confirmed.

**Comment by alefir** [comment]
@colanzio5 Has any of this been tested yet?

**Comment by colanzio5** [comment]
Yeah, the client and software that's in this branch are exactly the same, except for organization and additions.  (Older files were thrown into Depreciated). I'll add a new issue after merging this branch, for @waltoncade to remove any useless files from Depreciated as well as moving any current files from depreciated to their proper containing folder.

**Comment by colanzio5** [comment]
Also could you could give me write access to the main repo, I need it for science. Thanks

**Pull request merged**
