### PR TITLE
Reorganize

### PR DESCRIPTION
**Pull request by alefir**
- Moved Python TestStand client to Python folder in /Client
- Moved Python TestStand server to /Server
- Removed /Depreciated
- Removed empty/dummy files

To address #6

### CODE REVIEW

**Comment by colanzio5** [comment]
Make sure none of Cade's stuff in Depreciated is being deleted by accident. Automatic merges with one or two approvals seems well balanced.

**Comment by alefir** [comment]
That's why @waltoncade is also a reviewer for this one

**Comment by colanzio5** [comment]
This is a good way to use branches too - keep pulls brief and focused on the issue being addressed.

**Comment by alefir** [comment]
Here's a simplified changelog (hopefully a bit easier to go through than 1100 changed files)

- /Rocket and contents deleted (DummyData.py)
- Contents of /Client (two empty files) deleted
- /Server/ESBServer.py (empty file) Deleted
- /Server/TestStandServer.py replaced with /Depreciated/TestStand/TestStandServer.py
- /Depreciated/TestStand/TestStandClientV.1.py moved to /Client/Python/TestStandClient.py
- /Depreciated/TestStand/pictures moved to /Client/Python/
- /Depreciated deleted

**Comment by CEngelbrecht** [comment]
Changes look good to me

**Comment by alefir** [comment]
There you go

**Comment by colanzio5** [comment]
Awesome possum

**Pull request merged**
